### ISSUE TITLE
Dna.Simplification.AstMatchCandidates

### ISSUE THREAD

**Issue by xlfj5211** [Colton1skees/Dna#3]
foreach(var subAst in candidate.Value.ChildQueue.ToList())
                    {
                        if(subAst.ChildQueue.Count != visiting.Children.Count)
                        {
                            candidateMapping.
                        }
                    }

This location code is incomplete, missing code

**Comment by Colton1skees** [comment]
This was fixed with be71d3079e08a8393a88ed5d19926befd24381ac.
