### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by romanholidaypancakes** [Colton1skees/Dna#5]
Can you introduce the advantages of this project over other projects, such as [avast/retdec](https://github.com/avast/retdec),[vtil-project/VTIL-Core](https://github.com/vtil-project/VTIL-Core)
 [JonathanSalwan/Triton](https://github.com/JonathanSalwan/Triton) , is there a real world use case like deobfuscating virtual machines for vmprotect.

**Comment by Colton1skees** [comment]
Hi @romanholidaypancakes 

> Can you introduce the advantages of this project over other projects

The main advantage of Dna is that it provides *mostly* everything you need for binary analysis out of the box. Dna has components for:
- Parsing executable file formats
- Control flow graph recovery
- Symbolic execution
- Expression simplification(oracle based synthesis)
- Lifting of binary code to LLVM IR
- Constructing and translating to / from a family of IRs(AST representation, three address code representation, and LLVM-IR). It's also possible to translate LLVM IR back Dna's internal IR using [this class](https://github.com/Colton1skees/Dna/blob/master/Dna/Lifting/LLVMInstToIR.cs#L55).
- [Optimizing binary code using custom LLVM passes](https://github.com/Colton1skees/Dna/tree/master/Dna.LLVMInterop/Passes)

Dna is fast and multi-purpose. 

> is there a real world use case like deobfuscating virtual machines.
Yes, I've used this framework to break virtualization-based obfuscators.

**Comment by Colton1skees** [comment]
> Can you share related articles showing the specific structure after de-obfuscation?

Not yet. I plan to release a blog post in the upcoming few months though, after I wrap up some work on an existing software protector.

**Comment by Colton1skees** [comment]
Closing this for now. If I do get around to posting a writeup, I'll link it here.
